# Generated by Django 3.2.8 on 2021-10-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0003_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='usernmae',
            new_name='username',
        ),
    ]
