# Generated by Django 3.2.8 on 2021-10-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0004_rename_usernmae_signup_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
