# Generated by Django 3.2.8 on 2021-10-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0005_signup_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
