# Generated by Django 3.2.8 on 2021-10-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0009_rename_movies_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
