# Generated by Django 3.2.8 on 2021-10-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0011_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='review',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
