# Generated by Django 3.2.8 on 2021-10-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0012_alter_movie_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
