# Generated by Django 3.2.8 on 2021-11-02 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0013_alter_signup_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='mrating',
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrating', models.FloatField(max_length=20)),
                ('mname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='movieweb.movie')),
            ],
        ),
    ]
