# Generated by Django 3.2.8 on 2021-11-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0014_auto_20211102_0445'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
    ]
