# Generated by Django 3.2.8 on 2021-11-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0015_rename_ratings_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='mname',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
