# Generated by Django 3.2.8 on 2021-11-02 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movieweb', '0016_auto_20211102_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=20, unique=True)),
                ('shortdesc', models.CharField(max_length=20, unique=True)),
                ('longdesc', models.CharField(max_length=250, unique=True)),
                ('review', models.CharField(max_length=250, null=True)),
                ('vurl', models.CharField(max_length=250)),
                ('imageurl', models.CharField(max_length=250)),
                ('creation_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('type', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField()),
                ('creation_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrating', models.FloatField(max_length=20)),
                ('noofupdate', models.IntegerField(max_length=250)),
                ('mname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='movieweb.movie')),
            ],
        ),
    ]
