# Generated by Django 3.2.8 on 2021-11-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0017_movie_rating_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
        migrations.AlterField(
            model_name='rating',
            name='mrating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='noofupdate',
            field=models.IntegerField(),
        ),
    ]
